# 🧠 تحسين أداء Gradle (مهم جداً للبناء)
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# ⚡ دعم AndroidX (إجباري في Flutter الحديث)
android.useAndroidX=true
android.enableJetifier=true

# 🚀 تحسين البناء السريع (Performance)
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# 📦 تحسين Kotlin
kotlin.incremental=true

# 🔥 تحسين Flutter Build
flutter.buildMode=release
